# Generated by Django 6.0.3 on 2026-03-06 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARSession',
            fields=[
                ('session_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('host_app_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('capture_id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('captured_image', models.ImageField(upload_to='captures/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='ar_service.arsession')),
            ],
        ),
        migrations.CreateModel(
            name='ModelHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_url', models.URLField(max_length=500)),
                ('scale', models.FloatField(default=1.0)),
                ('rotation', models.FloatField(default=0.0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_handler', to='ar_service.arsession')),
            ],
        ),
    ]
