# Generated by Django 6.0.3 on 2026-03-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelhandler',
            name='placement_settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='arsession',
            name='product_name',
            field=models.CharField(default='Unknown Product', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelhandler',
            name='model_url',
            field=models.URLField(max_length=1000),
        ),
    ]
