# Generated by Django 6.0.3 on 2026-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_service', '0002_capture_product_name_modelhandler_placement_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='modelhandler',
            name='placement_settings',
        ),
        migrations.AlterField(
            model_name='arsession',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='modelhandler',
            name='model_url',
            field=models.URLField(max_length=500),
        ),
    ]
