# Generated by Django 6.0.3 on 2026-03-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar_service', '0003_remove_capture_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=100)),
                ('assembly', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('model_url', models.URLField(max_length=500)),
                ('scale', models.FloatField(default=1.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='arsession',
            name='product_id',
        ),
        migrations.AddField(
            model_name='arsession',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ar_service.product'),
        ),
    ]
