# Generated by Django 6.0.7 on 2026-07-30 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ar_service', '0005_category_capture_user_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The captured AR screenshot image.', upload_to='ar_captures/')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('position_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('scale', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, help_text='The product that was placed in AR when this capture was taken.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_captures', to='ar_service.product')),
            ],
            options={
                'verbose_name': 'AR Capture',
                'verbose_name_plural': 'AR Captures',
                'ordering': ['-created_at'],
            },
        ),
    ]
